### PR TITLE
feat: Added isEmpty

### PR DESCRIPTION
**Pull request by eElec**
Added @plexis/is-empty which checks if a string is empty.
Issue: #19

### CODE REVIEW

**Comment by vorillaz** [comment]
@eElec Thanks so much, if you could rebase your branch it would be awesome since I need to merge your PR.

**Comment by eElec** [comment]
I might have destroyed my fork. Should I create another pull request ?
Sorry I am pretty new to using git :stuck_out_tongue:

**Comment by vorillaz** [comment]
@eElec We are here to help you learn.
You can close this one and start over. You can also find information about syncing forks right [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by vorillaz** [comment]
I am closing this one mate @eElec

**Pull request closed without merging**
