### PR TITLE
feat: `toEllipsis / truncate / fit`

### PR DESCRIPTION
**Pull request by protob**
Please merge new toEllipsis feature.

### CODE REVIEW

**Comment by protob** [comment]
It's just a comment to remove wontfix label

**Comment by papb** [comment]
> 
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by papb** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by papb** [comment]
> 
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by protob** [comment]
@vorillaz, Could you merge this feature please?

**Comment by papb** [comment]
> 
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by AngelGzS** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

👀

**Comment by papb** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by papb** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by papb** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by AngelGzS** [comment]
👀

**Comment by papb** [comment]
> 
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. May the force be with you!

:eyes:

**Comment by vorillaz** [comment]
Oops, sorry for that merging this one!

**Pull request merged**
