### PR TITLE
Added package toSwap

### PR DESCRIPTION
**Pull request by drwm-base**
I wasn't able to get the toSwap function to work once I added it to index.js in the plexis folder. I checked the instructions but I wasn't missing anything. I don't really know why it's not working. It is set up exactly like every other function.

The function itself works, and has 5 test cases, testing different possible entries that might have not been accounted for. These test cases also run, the only one that doesn't is in plexis/test/index.js. 

For some reason, it cannot find the toSwap function.

Fixes Issue #75

### CODE REVIEW

**Comment by drwm-base** [comment]
I know what the problem is, I was missing the dist folder.

**Comment by brandon-m-skinner** [comment]
Hi @drwm-base 

You're missing the entry into docs/pages/api.md for your new package.

Brandon

**Comment by drwm-base** [comment]
Thanks for the reminder, almost missed that!

**Comment by drwm-base** [comment]
@vorillaz @brandon-m-skinner I added toSwap to the API. Is there anything else that I can do?

**Comment by drwm-base** [comment]
@brandon-m-skinner I have updated to the most recent version, please let me know if there is anything I need to fix!

**Pull request merged**
