### PR TITLE
Init the coolest documentation ever

### PR DESCRIPTION
**Pull request by 4doge**
@vorillaz I've often using docsify to documenting some stuff on work. Can you please check how it looks for Plexis? It's inside the `./docs` folder. If we will use this approach, then all documentation will be in one place, not the readme's inside each package. Also you can easily deploy it to Github pages, only the `docs` folder. Let me know what you think.

### CODE REVIEW

**Comment by vorillaz** [comment]
Wow, @4doge let me give it a try and I'll come back to you ASAP. I also made a list for documentation generators in the past, thus I need to check my list again.
That was super nice from your side though.

**Comment by 4doge** [comment]
@vorillaz I'll add only one page for demo purposes(but if you like it I can add more) and a search plugin for docsify, so you can easily find whatever you want.
We can also more like "copy button near code", "syntax highlight for different languages", "custom alerts" etc.
Also it's great that you can just write the markdown files and docsify will take care about everything else.
You need to have docsify installed globally to serve the static local.
```
npm i docsify-cli -g
# and run in the root of project
docsify serve ./docs
```

**Comment by vorillaz** [comment]
@4doge I think it's a great solution and I will give it a try and come back to you soon, one way or another we should try to be more flexible with the documentation solution, but it needs research.

**Comment by vorillaz** [comment]
I'll close this one and come back to you since I need to find out a building process through the CI/CD flow and also manage pending documentation issues.

**Pull request closed without merging**
