### PR TITLE
feat: isAlphaNumeric

### LINKED ISSUE #20: Feature request: `isAlphaDigit`
Checks whether the input text contains only alpha and digit characters.

**Example usage**

```javascript
import isAlphaDigit from '@plexis/is-alphadigit';

isAlphaDigit('ABCD');
// => true

isAlphaDigit('Apollo11');
// => true

isEmpty('Hello world');
// => false

isEmpty('Hello,world');
// => false

isAlphaDigit('');
// => false

isEmpty('   ');
// => false
```

**Aliases**

```javascript
import isAlphaDigit from '@plexis/is-alphadigit';
import {isAlphaDigit} from 'plexis';
```

### PR DESCRIPTION
**Pull request by floookay**
Added the isAlphaNumeric feature to check for strings that consist of alphabetical and/or numerical characters.  
Aliases are `isAlphaNumeric`, `isAlphanumeric` and `isAlphaDigit`

Closes #20

### CODE REVIEW

**Comment by floookay** [comment]
@vorillaz Hi, can you help me understand why the test failed? I'm not sure if I understand the problem. I already did a rebase.

**Comment by vorillaz** [comment]
Hey @floookay you can see the failing spec over here circleci.com/gh/plexis-js/plexis/122

Every time you are adding a new dependency to the main `plexis` package gets expanding. The main contains all the subpackages available.
So there is a single test inside `plexis` asserting the output methods. (https://github.com/plexis-js/plexis/blob/92cf70cfaeca25bb105cf68a0bb069de13b941d3/packages/plexis/test/index.js#L4)

This one is based on snapshot testing. Since you have added a new method into the exported ones you shall update the snapshot (https://github.com/plexis-js/plexis/blob/master/packages/plexis/test/__snapshots__/index.js.snap)

You can pipe any Jest parameters directly to the NPM script. So you can run `yarn test -u` and BOOM the snapshot gets updated.

More about snapshot testing can be found [here](https://jestjs.io/docs/en/snapshot-testing)
The presence of this test ensures that we are cross-checking each method added to the main package.
Does this make sense to you?

**Comment by vorillaz** [comment]
Thanks for the suggestion @brandon-m-skinner that's an awesome idea. 
Is there any chance you could expand the docs via a PR with what you have in mind since I am a bit busy reviewing PRs and creating new issues?

**Comment by brandon-m-skinner** [comment]
Sure thing @vorillaz.

**Comment by floookay** [comment]
@vorillaz Thank you so much for the detailed explanation! I see were I messed up earlier. Also, running `yarn bootstrap` did the trick. I was wondering why the `--updateSnapshot` command didn't produce any changes prior. Thanks @brandon-m-skinner!

**Comment by vorillaz** [comment]
Hey @floookay , can you please rebase your branch and we are good to go.

**Comment by floookay** [comment]
@vorillaz The branch is rebased

**Comment by vorillaz** [comment]
@floookay Can you please do another rebase since I released a version? Apologies for that :(

**Comment by floookay** [comment]
@vorillaz No worries! I rebased the branch.

**Comment by vorillaz** [comment]
@floookay Thanks so much :)

**Pull request merged**
