### PR TITLE
Feature request: `toChunks / chop`

### PR DESCRIPTION
**Pull request by korczynsk1**
Implementation of Feature request: `toChunks / chop` #56

### CODE REVIEW

**Comment by vorillaz** [comment]
@korczynsk1 Can you please rebase and update your branch?

**Comment by vorillaz** [comment]
@korczynsk1 Some tests are failing, I think you need to rebase your branch, run `yarn test-u` and update the snapshots.

**Comment by korczynsk1** [comment]
feature rebased, thanks for hint @vorillaz  🙇

**Comment by vorillaz** [comment]
@korczynsk1 You don't have to manually add any new versions, but that's ok since `lerna` can handle these issues.
Thanks for your contribution :)

**Comment by korczynsk1** [comment]
> @korczynsk1 You don't have to manually add any new versions, but that's ok since `lerna` can handle these issues.
> Thanks for your contribution :)

The pleasure is on mine. Thank you and see you on next features 😃

**Pull request merged**
