### PR TITLE
feat: add swap case utility

### PR DESCRIPTION
**Pull request by nowtryz**
## Description
Added toSwapCase() to swap from lowercase to uppercase and vice versa for the input text.

## Fixes # (issue)
#74

## Type of change
New feature (non-breaking change which adds functionality)

## Test

- [x] tested with single char
- [x] test with sentences

### CODE REVIEW

**Comment by vorillaz** [comment]
Can you please your branch and fix the failing tests? @nowtryz

**Comment by vorillaz** [comment]
Also, can you add your package to `docs/pages/api.md` ?

**Comment by nowtryz** [comment]
> Can you please your branch and fix the failing tests? @nowtryz

I'm trying to, but I don't find the problem

**Comment by nowtryz** [comment]
Ok, nice! Found the errors! You can merge the rest of the commits 🚀

**Comment by vorillaz** [comment]
@nowtryz There is a conflict with `plexis/package.json`

**Comment by nowtryz** [comment]
what should I do? I can't resolve the conflict for your master branch

**Comment by vorillaz** [comment]
> what should I do? I can't resolve the conflict for your master branch

You shall rebase and manually resolve any conflicts.

**Pull request merged**
