### PR TITLE
feat(is-empty): added is-empty

### PR DESCRIPTION
**Pull request by eElec**
resolves: #19

### CODE REVIEW

**Comment by vorillaz** [comment]
Thanks for the contribution :)

**Comment by vorillaz** [comment]
@eElec I accidentally closed this issue, can you please rebase your branch and we are ready to go.
Apologies for the inconvenience.

**Comment by vorillaz** [comment]
Hey @eElec you have missed placing your method in the `docs/api`

**Comment by eElec** [comment]
@vorillaz Added it. Probably deleted it while merging at some point.

**Pull request merged**
