### PR TITLE
Plexis cache

### PR DESCRIPTION
**Pull request by roemhildtg**
Hoping to learn more about API design. How does this look? I borrowed a lot from the lodash source.  Ready for review!

https://github.com/plexis-js/plexis/issues/3

### CODE REVIEW

**Comment by vorillaz** [comment]
@roemhildtg Can you please rebase your branch?

**Comment by roemhildtg** [comment]
Yes! I can later today. Not sure why how to fix the failing build. Seems the package needs to be published to make it install/build correctly, but the package doesn't exist yet?

**Comment by vorillaz** [comment]
@roemhildtg Try running `yarn bootstrap && yarn && yarn test -u`

**Comment by roemhildtg** [comment]
Okay - rebased and still getting that error. Do I need to remove the @plexis/cache from the package.json in plexis?

```
$ yarn bootstrap && yarn && yarn test -u
yarn run v1.17.3
$ lerna bootstrap
lerna notice cli v3.18.2
lerna info Bootstrapping 12 packages
lerna info Installing external dependencies
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'plexis'
lerna ERR! yarn install --mutex network:42424 --non-interactive stdout:
info No lockfile found.
[1/4] Resolving packages...
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\roemh\\web\\plexis\\packages\\plexis\\yarn-error.log".      
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

lerna ERR! yarn install --mutex network:42424 --non-interactive stderr:
error An unexpected error occurred: "https://registry.yarnpkg.com/@plexis%2fcache: Not found".

lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'plexis'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Pull request merged**
